### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by zMietek** [jeobz/NxDeckGantt#3]
How to get this app running with my selfhosted Nextcloud instance (Apache, non-docker).
I tried following steps:
-  cd /var/www/nextcloud/apps
- /var/www/nextcloud/apps$ sudo -u www-data wget https://github.com/jeobz/NxDeckGantt/archive/refs/heads/master.zip
- /var/www/nextcloud/apps$ sudo -u www-data unzip master.zip
- /var/www/nextcloud/apps$ sudo -u www-data mv NxDeckGantt-master/ NxDeckGantt/
- /var/www/nextcloud/apps$ sudo service apache2 reload

My nextcloud is not showing any Gantt apps :( 
What I did wrong?
Can someone help me correct it? My wife is looking for feature exactly like this..

Regards
Mietek

**Comment by Gunnar-GO** [comment]
it is an external (!) application that uses the DECK API for the data.

U must extract / clone this in an separate folder that can run on the webserver. That's all.

**Comment by boppy** [comment]
Basically, you did everything right. Your NxDeckGantt script is now available at

https://your-nextcloud.example.com/apps/NxDeckGantt/

And should run just fine.

Additional (kinda useless information):

- Because of CORS it's a good idea to host that script on the same domain as the NC instance - just as you did!
- The apache reload was not needed, because you did not change any apache configs, you just added some files.
- Your nextcloud might alert, because it cannot find the app-config belonging to the NxDeckGantt directory. You can just ignore that (but you should understand what the alert means nervertheless).

**Comment by zMietek** [comment]
Hi boppy,

my wife found in September2021 another working solution, but nevertheless I want to say:

thank you for clarifying my mistake: with correct URL "my" NxDeckGantt installation is visible :) It was there whole time ...
I'm feel me so stupid now :)

Best regards
Mietek
